# Generated by Django 4.2.14 on 2024-08-09 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="edpapp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("surname", models.CharField(max_length=100)),
                ("firstname", models.CharField(max_length=100)),
                ("othername", models.CharField(blank=True, max_length=100, null=True)),
                ("matricno", models.CharField(max_length=50, unique=True)),
                ("slc1", models.CharField(max_length=100)),
                ("slc2", models.CharField(max_length=100)),
                ("slc3", models.CharField(max_length=100)),
                ("slc4", models.CharField(max_length=100)),
                ("edpchoice", models.CharField(max_length=100)),
                ("phonenumber", models.CharField(max_length=15)),
                (
                    "session",
                    models.CharField(
                        choices=[
                            ("2023-2024", "2023-2024"),
                            ("2024-2025", "2024-2025"),
                            ("2025-2026", "2025-2026"),
                            ("2026-2027", "2026-2027"),
                            ("2027-2028", "2027-2028"),
                            ("2028-2029", "2028-2029"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "semester",
                    models.CharField(
                        choices=[
                            ("FIRST-SEMESTER", "First Semester"),
                            ("SECOND-SEMESTER", "Second Semester"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
    ]
