# Generated by Django 4.2.14 on 2024-10-29 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("edpapp", "0002_candidate_delete_edpapp"),
    ]

    operations = [
        migrations.RenameField(
            model_name="candidate", old_name="phone", new_name="phoneno",
        ),
    ]
