# Generated by Django 4.2.14 on 2024-10-29 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("edpapp", "0004_rename_phoneno_candidate_phone_alter_candidate_dob"),
    ]

    operations = [
        migrations.RenameField(
            model_name="candidate", old_name="phone", new_name="phoneno",
        ),
    ]
